env: live

spring:
  profiles:
    active: live # set this to the right environment esp for docker => live

  mail: # https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4N11isNtPUV0AmxD8ENeOcbgQEIGHimyned69xLBrAFHfAk5-iUXfYazUCckQFXbhtacVU8fIscVN24R6qx1SwxRUX71g
    host: smtp.gmail.com
    port: 587
    username: info.deloopltd@gmail.com
    password: 62131121Aa
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # for swagger bug

domain:
  url: http://localhost:${server.port}

jwt:
  secret:
    key: 123456Aa

remember:
  me:
    secret:
      key: nothing

server:
  port: 9090

db:
  server: localhost
  name: deloop_user
  user: root
  password: 123
  executeddl: false # overwrites/resets db if set to true CAUTION ⚠️
  seed: false # run migration script

logging:
  file:
    path: opt/logs
    name: deloop-user_${env}.log

default:
  hello:
    greeting: greeting from ${env}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

