env: live

server:
  port: ${PORT}

db:
  server: ${DB_SERVER} # deloop-user-mysql  # for docker
  name: ${DB_NAME} # deloop_user
  user: ${DB_USER} # root
  password: ${DB_PASSWORD} # 123

domain:
  url: https://deloopltd.com
